apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/app-service.yaml
  - manifests/backend-service.yaml
  - manifests/database.yaml
  - manifests/deployment.yaml
  - manifests/ingress.yaml
  - manifests/persistentvolumeclaim.yaml
images:
  - name: APP-PROJECT/IMAGE
    newName: sannahan/todo-app:e2.02.7
  - name: BACKEND-PROJECT/IMAGE
    newName: sannahan/todo-backend:e3.03